### PR TITLE
Add Vanilla Dpup

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Review by 01micko — APPROVED** [review]

**Comment by 01micko** [comment]
@peabee , in addition, you should probably add VoidPup.

**Comment by peabee** [comment]
> @peabee , in addition, you should probably add VoidPup.

Maybe on download.html but not on idex.html ? As it's not a "pure" Woof-CE build and is not on GitHub.....

**Review by peabee — COMMENTED** [review]
Mick has approved.

**Comment by 01micko** [comment]
> > @peabee , in addition, you should probably add VoidPup.
> 
> Maybe on download.html but not on idex.html ? As it's not a "pure" Woof-CE build and is not on GitHub.....

Sure, go for it :smile:

**Comment by peabee** [comment]
@dimkr 
VanillaDup should also be on download.html

**Pull request merged**
