### PR TITLE
Update downloads 030319

### PR DESCRIPTION
**Pull request by peabee**

### CODE REVIEW

**Review by jamesbond3142 — APPROVED** [review]
You may want to update copyright changes too. Right now it shows 2016 which look as if things have stopped, which obviously is not the case.

**Comment by jamesbond3142** [comment]
Nevermind I did it myself.

**Comment by jamesbond3142** [comment]
You may want to update the index page too.

**Comment by peabee** [comment]
> You may want to update the index page too.

I think the versions on the index page are strictly correct as they are the "official" versions that have been "announced" on Distrowatch.
If BionicPup64 achieves that status then it should be added.
All other builds are unofficial although some have attained the status of having their build recipes made available on GitHub - e.g. UPupBB

**Comment by peabee** [comment]
Oh and thanks for activating the pull request for the download page ;-)

**Comment by jamesbond3142** [comment]
> I think the versions on the index page are strictly correct as they are the "official" versions that have been "announced" on Distrowatch.
> If BionicPup64 achieves that status then it should be added.
> All other builds are unofficial although some have attained the status of having their build recipes made available on GitHub - e.g. UPupBB

Ah, ok. Thanks for the clarification.

**Pull request merged**
