### PR TITLE
Update history.html

### PR DESCRIPTION
**Pull request by ghost**
Great read! :D I try to fix a few minor spelling/grammar errors

### CODE REVIEW

**Comment by 01micko** [comment]
Thanks!

I would certainly pull this but there is just one problem. We have just re-organised the workflow! I suppose this is our shortcoming.

Could you please close this request and follow these instructions - sorry for the hassle! :crying_cat_face: 
- fork the repository at [github.com/puppylinux-woof-CE/woof-CE](https://github.com/puppylinux-woof-CE/woof-CE)
- change to the `gh-pages` branch and perform your edits and issue your pull request in the that repo. We will merge it straight away. Then I will merge it with this repository.
- this branch is live for testing at [puppylinux.eezy.xyz](http://puppylinux.eezy.xyz/) but is for us to test changes before merging into this repository. Consider it a `beta` branch vs `release` branch.

Of course your changes are straight forward but the way git works demands a consistent work flow.

Part of the reason for this is that we need a 'playground' for new ideas which would not be a professional look on the main site if something goes wrong. Thanks for your understanding, and again sorry for any hassles.

Cheers!

**Comment by ghost** [comment]
Thanks 01micko! Nice work on the website! Sure I will attempt this. :D

**Comment by 01micko** [comment]
Excellent! You shouldn't have any problems because the `gh-pages` branch is identical structure.

Cheers!

**Comment by mavrothal** [comment]
@ninaholic, 
you may want to wait few hours before you repeat this with gh-pages as we are in reconfiguration stage right now.
I'll reopen this one for now.

**Comment by mavrothal** [comment]
Looks like one of the 2 commits is already pulled. So this can not be merged anymore.
Is only the "any way" missing.

**Comment by 01micko** [comment]
Well it was a test of the new workflow @mavrothal .

**Comment by ghost** [comment]
Hi 01micko and mavrothal! I notice a side-effect of the merge, lines 21-22 have disappeared:

20 - with support for _"persistence"_ - that is, keep data between reboot 
?? - sessions. This way, the Live-CD can be used as if it is a fully installed
?? - operating system. However, if user data is corrupted in any way, 
21 - in a flick of a switch the persistence can be turned off and Puppy

My gh-pages branch has disappeared also so I leave this challenge for you experts I guess :D

**Comment by mavrothal** [comment]
fixed in 70a899c
thx

**Pull request closed without merging**
